<?php
require_once 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

include('db.php');

$reference = $_GET['reference'] ?? null;
if (!$reference) {
    die('Missing transaction reference.');
}

$stmt = $sql->prepare("SELECT * FROM virtual_account_topups WHERE reference = ?");
$stmt->execute([$reference]);
$txn = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$txn) {
    die('Transaction not found.');
}

$amount = number_format($txn['amount'], 2);
$paid_at = date('M d, Y h:i A', strtotime($txn['paid_at']));

$html = '
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: DejaVu Sans, sans-serif; padding: 20px; }
        h2 { text-align: center; color: #28a745; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        td { padding: 8px; border-bottom: 1px solid #ccc; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #555; }
    </style>
</head>
<body>
    <h2>Transaction Receipt</h2>
    <table>
        <tr><td><strong>Transaction Type</strong></td><td>Virtual Account Top-up</td></tr>
        <tr><td><strong>Amount</strong></td><td>₦' . $amount . '</td></tr>
        <tr><td><strong>Reference</strong></td><td>' . htmlspecialchars($txn['reference']) . '</td></tr>
        <tr><td><strong>Date</strong></td><td>' . $paid_at . '</td></tr>
        <tr><td><strong>Sender Name</strong></td><td>' . htmlspecialchars($txn['sender_name']) . '</td></tr>
        <tr><td><strong>Sender Bank</strong></td><td>' . htmlspecialchars($txn['sender_bank']) . ' (' . $txn['sender_account'] . ')</td></tr>
        <tr><td><strong>Receiver Bank</strong></td><td>' . htmlspecialchars($txn['receiver_bank']) . ' (' . $txn['receiver_account'] . ')</td></tr>
        <tr><td><strong>Customer</strong></td><td>' . htmlspecialchars($txn['customer_name']) . ' (' . $txn['customer_email'] . ')</td></tr>
    </table>
    <div class="footer">
        Receipt generated by Digital Solutions Hub
    </div>
</body>
</html>
';

$options = new Options();
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Download PDF
$dompdf->stream("receipt_{$reference}.pdf", ["Attachment" => true]);
exit;
