<?php
require_once 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

include('db.php');

$reference = $_GET['reference'] ?? null;
if (!$reference) {
    die('Missing transaction reference.');
}

$stmt = $sql->prepare("SELECT * FROM user_withdrawals WHERE reference = ?");
$stmt->execute([$reference]);
$txn = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$txn) {
    die('Transaction not found.');
}

// Assign fields
$amount = number_format($txn['amount'], 2);
$created_at = $txn['paid_at'];
$transaction_ref = $txn['reference'];
$account_name = $txn['account_name'];       // make sure these match your DB columns
$bank_name = $txn['bank_name'];
$account_number = $txn['account_number'];
$session_id = $txn['session_id'];

$html = '
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: DejaVu Sans, sans-serif; padding: 20px; }
        h2 { text-align: center; color: #28a745; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        td { padding: 8px; border-bottom: 1px solid #ccc; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #555; }
    </style>
</head>
<body>
    <h2>Transaction Receipt</h2>
    <table>
        <tr><td><strong>Transaction Type</strong></td><td>Money Transfer</td></tr>
        <tr><td><strong>Amount</strong></td><td>₦' . $amount . '</td></tr>
        <tr><td><strong>Reference</strong></td><td>' . htmlspecialchars($transaction_ref) . '</td></tr>
        <tr><td><strong>Date</strong></td><td>' . date('M d, Y h:i A', strtotime($created_at)) . '</td></tr>
        <tr><td><strong>Recipient Name</strong></td><td>' . htmlspecialchars($account_name) . '</td></tr>
        <tr><td><strong>Bank</strong></td><td>' . htmlspecialchars($bank_name) . ' (' . $account_number . ')</td></tr>
        <tr><td><strong>Session ID</strong></td><td>' . htmlspecialchars($session_id) . '</td></tr>
    </table>
    <div class="footer">
        Receipt generated by Digital Solutions Hub
    </div>
</body>
</html>
';

$options = new Options();
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$dompdf->stream("receipt_{$reference}.pdf", ["Attachment" => true]);
exit;
